version: '2'
 
services:
 web:
   restart: always
   build: .
   expose:
     - "8000"
   volumes:
     - /usr/src/app/project/static
   command: python manage.py runserver
 
 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   volumes:
     - /www/static
   volumes_from:
     - web
   depends_on:
     - web
