version: '2'
 
services:
 postgres:
   image: postgres
   restart: always

 web:
   restart: always
   build: .
   expose:
     - "8000"
   volumes:
     - /usr/src/app/project/static
   command: python manage.py create_db
   depends_on:
     - postgres
 
 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   volumes:
     - /www/static
   volumes_from:
     - web
   depends_on:
     - web

