version: '2'
 
services:
 postgres:
   restart: always
   build: ./postgres
   expose:
     - "5432"

 web:
   restart: always
   build: .
   expose:
     - "5000"
   depends_on:
     - postgres
 
 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   volumes:
     - ./project/static/:/www/static/
   depends_on:
     - web

