version: '2'
 
services:
 postgres:
   restart: always
   build: ./postgres
   expose:
     - "5432"

 web:
   restart: always
   build: .
   volumes:
     - ./project:/opt/app/src/project
   expose:
     - "5000"
   depends_on:
     - postgres

 client:
   restart: always
   build: ./client
   volumes:
     - ./client/src:/app/src/
   expose:
     - "3000"

 
 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   depends_on:
     - web
     - client
